/*Novo projeto*/

/*O QUE EU QUERO DO CLIENTE:
DADOS PESSOAIS: NOME, ENDERECO, TELEFONE, CPF, RG, SEXO.
CAMPOS VETORIZADOS: TELEFONE.
CAMPOS MULTIVALORADOS: ENDERECO.

DADOS DOS ATIVOS: NOME, CODIGO, TIPO, CORRETORA. 
*/
CREATE DATABASE INVEST;

USE INVEST;

CREATE TABLE CLIENTES(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	RG VARCHAR(8) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('COM','RES','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	CIDADE VARCHAR (30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTES(IDCLIENTE)
);

CREATE TABLE ATIVOS(
	IDATIVOS INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	CODIGO VARCHAR(6),
	TIPO VARCHAR (20),
	CORRETORA VARCHAR (20),
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTES(IDCLIENTE)
);

/*INSERINDO VALOR*/
INSERT INTO CLIENTES VALUES(NULL,'FERNANDO DE RESENDE SILVA','12345678915','1305896','M','FRESENDE1@HOTMAIL.COM');
INSERT INTO CLIENTES VALUES(NULL,'LORENA RODRIGUES', '12345678901','30000222','F','LORENARODRIGUES@EMAIL.COM');
INSERT INTO CLIENTES VALUES(NULL,'JEFFERSON ARMON SILVA', '09795482608','15071915','M','JEFFERSON.ASRS@GMAIL.COM');
INSERT INTO CLIENTES VALUES(NULL,'MARINA COUTO SANTOS', '12345678908','30000228','F','MARINA@EMAIL.COM');
INSERT INTO CLIENTES VALUES(NULL,'GLAUCO DIOGO', '65478902558','56987654','M','GLAUCO@EMAIL.COM');

/*INSERINDO TELEFONES*/
INSERT INTO TELEFONE VALUES(NULL,'CEL','997573236',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','997573235',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','997581714',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','994251566',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','997554895',2);

/*INSERINDO ENDERECO*/
INSERT INTO ENDERECO VALUES(NULL,'ALOÍSIO LOBÃO VERAS','BELO HORIZONTE','MG','SERRANO',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','SÃO PAULO','SP','JARDINS',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA C','BRASÍLIA','DF','ASA NORTE',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA F','RIO DE JANEIRO','RJ','COPA CABANA',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','CONTAGEM','MG','RESSACA',200);

/*INSERINDO ATIVOS*/
INSERT INTO ATIVOS VALUES(NULL,'BANCO INTER','BIDI11','AÇÃO','IDTVM',7);
INSERT INTO ATIVOS VALUES(NULL,'SANTANDER','SANB3','AÇÃO','EASYNVEST',2);
INSERT INTO ATIVOS VALUES(NULL,'ITAU UNIBANCO','ITUB3','AÇÃO','IDTVM',8);
INSERT INTO ATIVOS VALUES(NULL,'HEDGE','HGBS11','FII','IDTVM',1);
INSERT INTO ATIVOS VALUES(NULL,'LOJAS RENNER','LREN3','AÇÃO','IDTVM',8);
INSERT INTO ATIVOS VALUES(NULL,'MAGAZINE LUIZA','MGLU3','AÇÃO','IDTVM',1);
INSERT INTO ATIVOS VALUES(NULL,'XP','XPML11','FII','IDTVM',2);
INSERT INTO ATIVOS VALUES(NULL,'BANCO INTER','BIDI4','AÇÃO','IDTVM',6);
INSERT INTO ATIVOS VALUES(NULL,'GENERAL','GGRC11','FII','IDTVM',7);

/* SELEÇÃO, PROJEÇÃO E JUNÇÃO*/

SELECT CLIENTES.NOME, CLIENTES.SEXO, 
ENDERECO.BAIRRO, ENDERECO.CIDADE, 
ATIVOS.CODIGO AS ATIVO, ATIVOS.TIPO,
NOW() AS DATA
FROM CLIENTES
INNER JOIN ENDERECO
ON CLIENTES.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN ATIVOS
ON CLIENTES.IDCLIENTE = ATIVOS.ID_CLIENTE
WHERE CORRETORA = 'IDTVM';

+---------------------------+------+------------+----------------+--------+--------+---------------------+
| NOME                      | SEXO | BAIRRO     | CIDADE         | ATIVO  | TIPO   | DATA                |
+---------------------------+------+------------+----------------+--------+--------+---------------------+
| JEFFERSON ARMON SILVA     | M    | SERRANO    | BELO HORIZONTE | BIDI11 | AÇÃO   | 2019-09-27 01:18:58 |
| FERNANDO DE RESENDE SILVA | M    | COPACABANA | RIO DE JANEIRO | HGBS11 | FII    | 2019-09-27 01:18:58 |
| MARINA COUTO SANTOS       | F    | RESSACA    | CONTAGEM       | LREN3  | AÇÃO   | 2019-09-27 01:18:58 |
| FERNANDO DE RESENDE SILVA | M    | COPACABANA | RIO DE JANEIRO | MGLU3  | AÇÃO   | 2019-09-27 01:18:58 |
| LORENA RODRIGUES          | F    | JARDINS    | SÃO PAULO      | XPML11 | FII    | 2019-09-27 01:18:58 |
| GLAUCO DIOGO              | M    | ASA NORTE  | BRASÍLIA       | BIDI4  | AÇÃO   | 2019-09-27 01:18:58 |
| JEFFERSON ARMON SILVA     | M    | SERRANO    | BELO HORIZONTE | GGRC11 | FII    | 2019-09-27 01:18:58 |
| MARINA COUTO SANTOS       | F    | RESSACA    | CONTAGEM       | ITUB3  | AÇÃO   | 2019-09-27 01:18:58 |
+---------------------------+------+------------+----------------+--------+--------+--------------------


/*ALTERANDO NOME DA COLUNA*/
ALTER TABLE ATIVOS
RENAME COLUMN NOME TO ATIVO;

UPDATE ENDERECO
SET BAIRRO = 'COPACABANA'
WHERE IDTELEFONE = 5;

/* VIEWS*/

/* FAZER RELATÓRIO COM NOME, CPF, EMAIL, TELEFONE E ATIVOS DE CADA CLIENTE*/

SELECT C.NOME,C.CPF,C.EMAIL,T.NUMERO,A.CODIGO AS ATIVO
FROM CLIENTES C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ATIVOS A
ON C.IDCLIENTE = A.ID_CLIENTE
WHERE T.TIPO = 'CEL'

/* CRIANDO UMA VIEW */

CREATE VIEW REGISTROS_V AS
SELECT C.NOME,
		C.CPF,
		C.EMAIL,
		T.NUMERO,
		A.CODIGO AS ATIVO
FROM CLIENTES C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ATIVOS A
ON C.IDCLIENTE = A.ID_CLIENTE;

SELECT * FROM REGISTROS_V
ORDER BY NOME;
+---------------------------+-------------+---------------------------+-----------+--------+
| NOME                      | CPF         | EMAIL                     | NUMERO    | ATIVO  |
+---------------------------+-------------+---------------------------+-----------+--------+
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 997573235 | HGBS11 |
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 997573235 | MGLU3  |
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 994251566 | HGBS11 |
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 994251566 | MGLU3  |
| GLAUCO DIOGO              | 65478902588 | GLAUCO@EMAIL.COM          | 997581714 | BIDI4  |
| JEFFERSON ARMON SILVA     | 09795482608 | JEFFERSON.ASRS@GMAIL.COM  | 997573236 | BIDI11 |
| JEFFERSON ARMON SILVA     | 09795482608 | JEFFERSON.ASRS@GMAIL.COM  | 997573236 | GGRC11 |
| LORENA RODRIGUES          | 12345678901 | LORENARODRIGUES@EMAIL.COM | 997554895 | SANB3  |
| LORENA RODRIGUES          | 12345678901 | LORENARODRIGUES@EMAIL.COM | 997554895 | XPML11 |
+---------------------------+-------------+---------------------------+-----------+--------+

SELECT * FROM REGISTROS_V
ORDER BY 5;

+---------------------------+-------------+---------------------------+-----------+--------+
| NOME                      | CPF         | EMAIL                     | NUMERO    | ATIVO  |
+---------------------------+-------------+---------------------------+-----------+--------+
| JEFFERSON ARMON SILVA     | 09795482608 | JEFFERSON.ASRS@GMAIL.COM  | 997573236 | BIDI11 |
| GLAUCO DIOGO              | 65478902588 | GLAUCO@EMAIL.COM          | 997581714 | BIDI4  |
| JEFFERSON ARMON SILVA     | 09795482608 | JEFFERSON.ASRS@GMAIL.COM  | 997573236 | GGRC11 |
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 997573235 | HGBS11 |
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 994251566 | HGBS11 |
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 997573235 | MGLU3  |
| FERNANDO DE RESENDE SILVA | 12345678915 | FRESENDE1@HOTMAIL.COM     | 994251566 | MGLU3  |
| LORENA RODRIGUES          | 12345678901 | LORENARODRIGUES@EMAIL.COM | 997554895 | SANB3  |
| LORENA RODRIGUES          | 12345678901 | LORENARODRIGUES@EMAIL.COM | 997554895 | XPML11 |
+---------------------------+-------------+---------------------------+-----------+--------+

UPDATE CLIENTES
SET EMAIL = 'FRESEND@HOTMAIL.COM'
WHERE IDCLIENTE = 1;
